In [1]:
import numpy as np
from dsp.decoding import BlockGenerator

In [2]:
bits = np.load('./data/msg_bits.npy').astype(np.int)

In [3]:
gen = BlockGenerator()

In [4]:
prev = 0
for s in range(len(bits) - 26 + 1):
    syndrome = gen.syndrome(bits[s:s + 26])
    if syndrome in gen.offset_syndrome:
        print(s, s - prev, gen.offset_syndrome[syndrome])
        prev = s

136 136 3
162 26 0
188 26 1
214 26 2
240 26 3
266 26 0
292 26 1
318 26 2
344 26 3
370 26 0
396 26 1
422 26 2
542 120 3
568 26 0
594 26 1
620 26 2
646 26 3
672 26 0
698 26 1
724 26 2
750 26 3
794 44 2
869 75 0
895 26 1
921 26 2
947 26 3
973 26 0
1069 96 0
1095 26 1
1121 26 2
1147 26 3
1173 26 0
1199 26 1
1225 26 2
1342 117 3
1368 26 0
1394 26 1
1420 26 2
1446 26 3
1472 26 0
1498 26 1
1524 26 2
1550 26 3
1642 92 3
1668 26 0
1694 26 1
1720 26 2
1746 26 3
1772 26 0
1798 26 1
1824 26 2
1850 26 3
1946 96 3
1972 26 0
1998 26 1
2024 26 2
2050 26 3
2076 26 0
2146 70 3
2172 26 0
2198 26 1
2224 26 2
2244 20 1
2299 55 1
2325 26 2
2351 26 3
2377 26 0
2427 50 2
2453 26 3
2479 26 0
2554 75 3
2580 26 0
2630 50 2
2650 20 1
2656 6 3
2706 50 1
2732 26 2
2782 50 0
2857 75 3
2885 28 2
2907 22 1
2957 50 0
2983 26 0
3034 51 2
3085 51 0
3135 50 2
3186 51 0
3236 50 2
3261 25 3
3344 83 1
3362 18 3
3463 101 3
3489 26 0
3515 26 1
3615 100 1
3641 26 2
3718 77 1
3744 26 2
3770 26 3
3784 14 1
3833 49 2
3846 13 2
387

In [5]:
gen.synchronize(bits)

(162, 0)

In [6]:
blocks = []
gen.process_blocks(bits[162:], blocks, 0)

1456

In [7]:
blocks = gen.find_blocks(bits)

('SYNCED: ', 162)
('LOST SYNC: ', 1618)
('SYNCED: ', 1668)
('LOST SYNC: ', 3046)
('SYNCED: ', 3489)
('LOST SYNC: ', 4711)
('SYNCED: ', 5228)
('LOST SYNC: ', 6424)
('SYNCED: ', 6452)
('LOST SYNC: ', 7648)
('SYNCED: ', 8516)
('LOST SYNC: ', 9738)
('SYNCED: ', 10595)
('LOST SYNC: ', 11817)
('SYNCED: ', 12347)
('LOST SYNC: ', 13621)
('SYNCED: ', 14612)
('LOST SYNC: ', 15834)
('SYNCED: ', 16148)
('LOST SYNC: ', 17344)
('SYNCED: ', 19416)
('LOST SYNC: ', 20612)
('SYNCED: ', 22948)
('LOST SYNC: ', 22948)


In [8]:
[b for i, b in blocks if i == 0]

[array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1]),
 array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1]),
 array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1]),
 array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1]),
 array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1]),
 array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0]),
 array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1]),
 array([1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0]),
 array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1]),
 array([1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]),
 array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1]),
 array([0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0]),
 array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1]),
 array([1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 

Results are pretty bad. Let's try it out on bits decoded by Redsea.

In [9]:
with open('./data/redsea_bits', 'r') as redsea:
    redsea_str = redsea.read().strip()
redsea_bitlist = list(map(int, redsea_str))
redsea_bits = np.array(redsea_bitlist, dtype=np.int)

In [10]:
blocks = gen.find_blocks(redsea_bits)

('SYNCED: ', 194)
('LOST SYNC: ', 23084)


Holy...

In [11]:
blocks

[(0, array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1])),
 (1, array([1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0])),
 (2, array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1])),
 (3, array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1])),
 (1, array([0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1])),
 (2, array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])),
 (3, array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])),
 (0, array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1])),
 (1, array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0])),
 (2, array([1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0])),
 (3, array([0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1])),
 (0, array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1])),
 (1, array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1])),
 (2, array([0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1])),
 (3, array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1])),
 (0, array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0

In [12]:
[(ind, b) for ind, (i, b) in enumerate(blocks) if i == 1]

[(1, array([1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0])),
 (4, array([0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1])),
 (8, array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0])),
 (12, array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1])),
 (16, array([1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0])),
 (20, array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0])),
 (24, array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1])),
 (28, array([0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0])),
 (32, array([1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0])),
 (36, array([0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1])),
 (40, array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0])),
 (44, array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1])),
 (48, array([1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0])),
 (52, array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0])),
 (56, array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1])),
 (60, array([0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 